# Generated by Django 5.0.7 on 2024-09-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='descripcion',
            new_name='texto',
        ),
    ]
