# Generated by Django 5.0.7 on 2024-09-08 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=15)),
                ('appointment_date', models.CharField(choices=[('2024-09-07T10:35:00-05:00', 'September 7 10:35AM'), ('2024-09-08T10:25:00-05:00', 'September 8 10:25AM'), ('2024-09-09T11:00:00-05:00', 'September 9 11AM'), ('2024-09-11T09:00:00-05:00', 'September 11 9AM'), ('2024-09-23T16:00:00-05:00', 'September 23 4PM'), ('2024-09-30T14:30:00-05:00', 'September 30 2:30PM')], default='2024-09-06T13:00:00+00:00', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Reminder', max_length=100)),
                ('reminder_date', models.DateField()),
                ('reminder_title', models.CharField(default='Reminder', max_length=100)),
                ('reminder_message', models.CharField(max_length=200)),
                ('reminder_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
