# Generated by Django 5.0.7 on 2024-08-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=15)),
                ('appointment_date', models.CharField(choices=[('August 26 3PM', 'August 26 3PM'), ('August 31 10AM', 'August 31 10AM'), ('September 2 11AM', 'September 2 11AM'), ('September 11 9AM', 'September 11 9AM'), ('September 23 4PM', 'September 23 4PM'), ('September 30 2:30PM', 'September 30 2:30PM')], default='August 26 3PM', max_length=20)),
            ],
        ),
    ]
