# Generated by Django 5.0.7 on 2024-09-08 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_title',
            field=models.CharField(max_length=255),
        ),
    ]
