# Generated by Django 5.0.7 on 2024-09-05 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(choices=[(datetime.datetime(2024, 9, 3, 10, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 9, 3, 10, 0, tzinfo=datetime.timezone.utc)), (datetime.datetime(2024, 9, 14, 7, 40, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 9, 14, 7, 40, tzinfo=datetime.timezone.utc)), (datetime.datetime(2024, 9, 19, 12, 30, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 9, 19, 12, 30, tzinfo=datetime.timezone.utc)), (datetime.datetime(2024, 9, 28, 13, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 9, 28, 13, 0, tzinfo=datetime.timezone.utc)), (datetime.datetime(2024, 10, 2, 14, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 10, 2, 14, 0, tzinfo=datetime.timezone.utc)), (datetime.datetime(2024, 10, 13, 15, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 10, 13, 15, 0, tzinfo=datetime.timezone.utc)), (datetime.datetime(2024, 10, 22, 16, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 10, 22, 16, 0, tzinfo=datetime.timezone.utc)), (datetime.datetime(2024, 10, 30, 9, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2024, 10, 30, 9, 0, tzinfo=datetime.timezone.utc))], default=datetime.datetime(2024, 9, 3, 10, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
