# Generated by Django 5.0.7 on 2024-08-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.CharField(choices=[('date1', 'August 26 3PM'), ('date2', 'August 29 1PM'), ('date3', 'August 31 10AM'), ('date4', 'September 2 11AM'), ('date5', 'September 11 9AM'), ('date6', 'September 23 4PM'), ('date7', 'September 30 2:30PM')], default='August 26 3PM', max_length=20),
        ),
    ]
