# Generated by Django 5.0.7 on 2024-09-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_reminder_name_alter_reminder_reminder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='name',
        ),
    ]
