# Generated by Django 5.0.7 on 2024-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_title', models.CharField(max_length=100)),
                ('reminder_message', models.CharField(max_length=200)),
                ('reminder_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
