# Generated by Django 5.0.7 on 2024-09-05 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reminder',
            name='name',
            field=models.CharField(default='Reminder', max_length=100),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_title',
            field=models.CharField(default='Reminder', max_length=100),
        ),
    ]
