# Generated by Django 5.0.7 on 2024-09-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_reminder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='name',
        ),
    ]
